@startuml

actor Org as "Organisation"

rectangle Database

rectangle "Cities Ranks" {
    usecase UC4 as "Get ranks of cities
    based on population"

    usecase UCa as "Print Cities"

    Org - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml