@startuml

actor Org as "Organisation"

rectangle Database

rectangle "Countries Ranks" {
    usecase UC4 as "Get ranks of countires
    based on population"

    usecase UCa as "Print Countries"

    Org - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml