@startuml
left to right direction
actor Org as "Organisation"

rectangle "Population in the World" {
    usecase UC1 as "All the countries in the world organised
    by largest population to smallest."
    usecase UC2 as "All the countries in a continent organised
    by largest population to smallest."
    usecase UC3 as "All the countries in a region organised
    by largest population to smallest."
    usecase UC4 as "All the cities in the world organised
    by largest population to smallest."
    usecase UC5 as "All the cities in a continent organised
    by largest population to smallest."
    usecase UC6 as "All the cities in a region organised
    by largest population to smallest."
    usecase UC7 as "All the cities in a country organised
    by largest population to smallest."
    usecase UC8 as "All the cities in a district organised
    by largest population to smallest."


    Org ---> UC1
    Org ---> UC2
    Org ---> UC3
    Org ---> UC4
    Org ---> UC5
    Org ---> UC6
    Org ---> UC7
    Org ---> UC8

}

@enduml